<?php
/**
 * @file
 * @copyright (C) Copyright 2014 Palantir.net
 */
function adonis_title_validator_form_node_form_alter(&$form, &$form_state, $form_id) {
  $form['#validate'][] = 'adonis_validation_invoke';
}

function adonis_validation_invoke($form, &$form_state) {
  $title = $form_state['input']['title'];
  $validator = new TitleValidator();
  try {
    $validator->checkClean($title);
  }
  catch (Exception $e) {
    form_set_error('clean title', t('Bad boy, hell gnaw.'));
  }
}
